1. values added:  20
2. final result:  20
3. values added:  20 
4. The code on line 13 returns an error, because it tries to print the *result* variable to the console. However, the *result* variable was declared with the *let* keyword which only provides which only provides the variables accessibility wihtin the block it is defined in. Line 13 is outside of the *result* variable's block scope which caused the error. 
5. The code on line 9 returns an error, because it print to the console the variable *result*. Yet, *result* is invalid, because line 7 reassigns the value of *result* and the variable was declared with the *const* keyword. The *const* keyword prevents a variable from being reassinged after the first time. The code on line 6 initalized the value of the *result* variable. Therefore, line 7 invalidates the *result* variable making when line 9 tries to the print value of *result* an error is returned. 
6. The code on line 13 returns an error because of two reasons. The first reason is line 7 invalidates the variable *result* because it reassigns its value when it was assinged on line five 5 with the keyword 'const' and a value of zero. The *const* keyword prevents a variable from being reassinged after the first time. The second reason is line 13 tries to access the *result* variable outside of its block scope. Since *result* was declared with the *const* keyword it can only be accessed within its block scope, which ended on line 11. 